---
# Source: kyverno-image-verification-service/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kyverno-image-verification-service
  namespace: kyverno-image-verification-service
---
# Source: kyverno-image-verification-service/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kyverno-image-verification-service-role
  namespace: kyverno-image-verification-service
  labels:
    app.kubernetes.io/instance: kyverno-image-verification-service
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kyverno-image-verification-service
    app.kubernetes.io/version: v0.1
    helm.sh/chart: kyverno-image-verification-service-v0.1
rules:
  - apiGroups:
      - ""
    resources:
      - "secrets"
      - "configmaps"
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
---
# Source: kyverno-image-verification-service/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kyverno-image-verification-service-rolebinding
  namespace: kyverno-image-verification-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kyverno-image-verification-service-role
subjects:
- kind: ServiceAccount
  name: kyverno-image-verification-service
  namespace: kyverno-image-verification-service
---
# Source: kyverno-image-verification-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kyverno-image-verification-service-svc
  namespace: kyverno-image-verification-service
  labels:
    app.kubernetes.io/instance: kyverno-image-verification-service
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kyverno-image-verification-service
    app.kubernetes.io/version: v0.1
    helm.sh/chart: kyverno-image-verification-service-v0.1
spec:
  ports:
    - port: 443
      name: https
      protocol: TCP
      targetPort: 9443
  selector:
    app.kubernetes.io/part-of: kyverno-image-verification-service
    app.kubernetes.io/instance: kyverno-image-verification-service
---
# Source: kyverno-image-verification-service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyverno-image-verification-service
  namespace: kyverno-image-verification-service
  labels:
    app.kubernetes.io/instance: kyverno-image-verification-service
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kyverno-image-verification-service
    app.kubernetes.io/version: v0.1
    helm.sh/chart: kyverno-image-verification-service-v0.1
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/part-of: kyverno-image-verification-service
      app.kubernetes.io/instance: kyverno-image-verification-service
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: kyverno-image-verification-service
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: kyverno-image-verification-service
        app.kubernetes.io/version: v0.1
        helm.sh/chart: kyverno-image-verification-service-v0.1
    spec:
      terminationGracePeriodSeconds: 5
      securityContext:
        runAsNonRoot: true
      serviceAccountName: kyverno-image-verification-service
      containers:
      - image: ghcr.io/nirmata/image-verification-service:latest
        imagePullPolicy: IfNotPresent
        name: kyverno-image-verification-service
        args:
          - --leader-elect=false
          - --notls=false
          - --allowInsecureRegistry=false
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 32Mi
            cpu: 100m
        securityContext:
          runAsUser: 2000
          runAsGroup: 3000
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace  
        - name: SERVICE_NAME
          value: kyverno-image-verification-service-svc
        - name: DEPLOYMENT_NAME
          value: kyverno-image-verification-service
        - name: POLICY_PATH
          value: oci://ghcr.io/vishal-chdhry/ivpol:crit-vuln
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
          - mountPath: /policies
            name: policies
      volumes:
        - image:
            reference: ghcr.io/vishal-chdhry/ivpol:latest
          name: policies
